### PR TITLE
Added initComputedStyle to avoid deriving layout values from unstyled elements.

### LINKED ISSUE #31: Incorrect initial height when part of a Bootstrap modal dialog
I'm using your fantastic directive on a textarea in Bootstrap's modal dialog (via Angular-Strap bs-modal directive) and the problem I'm facing is when modal dialog is displayed, the textarea has wrong height. 

I was able to track the problem down to the mdsElastic directive initialization of the globals - `borderBox` and `boxOuter` (and possibly others too). They are initialized from `getComputedStyle()` result which returns empty values. The problem is possibly due to fact, that modal window directive is adding the DOM structure with modal window content to the document on-the-fly (i.e. it is added in time of showing the modal dialog) and maybe therefore the `getComputedStyle()` returns empty values.

I've solved this issue temporarily by adding `recalculateDefaults()` method to `scope.$on('elastic:adjust')`. This method just assigns the same values to the `borderBox` and `boxOuter` globals but I'm firing the event for `elastic:adjust` after the modal dialog is fully shown (and therefore the `getComputedStyle()` returns correct values). Works as expected, but unfortunately the resizing of textarea is visible (and possibly annoying) for the user (i.e. modal is fully shown and after that, the textarea "jumps" to its correct height).

I just wanted to let you know that there is an issue with modal dialogs and maybe there is someone out there who knows how to fix this correctly.

### PR DESCRIPTION
**Pull request by idpaterson**
In some cases, such as bootstrap modals and popovers, the directive may be linked prior to being inserted into the document. In this state, there are no styles applied to the element. When this occurred, even emitting elastic:adjust did not recalculate the layout values. With this change, the directive is initialized properly without the elastic:adjust, but if cases exist where it is not, emitting elastic:adjust will calculate the layout if styles were not previously available.

This should resolve #31 in a generic way that does not adversely affect other environments or specifically target bootstrap. I noticed the same problem with Bootstrap popovers; the textarea was about 1/2 the height of a line of text since the padding was not yet available from `getComputedStyle`. 

In my case, after applying this fix it was not necessary to call `elastic:adjust` as the `ngModel.$modelValue` watcher was the first thing to fire asynchronously after the directive was linked. There is no rendering flash as the layout is still computed before the element is actually made visible.

### CODE REVIEW

**Comment by stalena** [comment]
I urgently need this change...
Please merge it in to master branch!!!!

Kind regards

**Comment by idpaterson** [comment]
@stalena, it's been quite awhile, I'm still using my fork from this pull request, just rebased this pull request against the latest master for you: https://github.com/Newstex/angular-elastic/tree/pull-requests/computed-style-check

**Comment by stalena** [comment]
@idpaterson, many Thanks!
It works just fine!

The maintainer may post it please.

Best regards

**Comment by optyler** [comment]
@idpaterson do you think your fix is somehow related to this issue #101 ?

The textarea is displayed in a bootstrap modal...

**Comment by idpaterson** [comment]
I don't think so but haven't used this in a few years. Feel free to give it  try.

**Pull request closed without merging**
